info:
  app:
    version: 1.0.0
    test: test
    name: email-management-api-actuator

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  server:
    servlet:
      context-path: /monitor

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka/
server:
  port: ${PORT}
spring:
  application:
    name: service-email-management

