info:
  app:
    version: 1.0.0
    test: test
    name: email-management-api-actuator

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  server:
    servlet:
      context-path: /monitor
